spring:
  application:
    name: flow-api-gateway
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Hibernate DDL (none, validate, update, create-drop)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
    access:
      expiration: ${ACCESS_EXPIRATION}
    refresh:
      expiration: ${REFRESH_EXPIRATION}
  cloud:
    gateway:
      routes:
        - id: main-route
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/**
          filters:
            - name: AuthenticationFilter
        - id: main-auth-route
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/auth/**