spring:
  application:
    name: flow-api-gateway
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    gateway:
      routes:
        - id: main-auth-route
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/auth/**
        - id: order-route
          uri: ${PAYMENT_ROUTE_ADDRESS}
          predicates:
            - Path=/order/**
          filters:
            - name: AuthenticationFilter
        - id: payment-route
          uri: ${PAYMENT_ROUTE_ADDRESS}
          predicates:
            - Path=/payment/**
          filters:
            - name: AuthenticationFilter
logging:
  level:
    org:
      flow:
        gateway:
          common:
            log:
              LoggingFilter: DEBUG