spring:
  application:
    name: flow-api-gateway
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      max-size: 10
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - ${FLOW_WEB_ADDRESS}
              - ${FLOW_ADMIN_DASHBOARD_ADDRESS}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: admin-route-non-auth
          uri: ${ADMIN_ROUTE_ADDRESS}
          predicates:
            - Path=/api/admin/**

        - id: auth-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/auth/**

        - id: hall-of-frame-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/hall-of-fame/**

        - id: job-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/job/**

        - id: search-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/search/**

        - id: order-route
          uri: ${PAYMENT_ROUTE_ADDRESS}
          predicates:
            - Path=/order/**
            - Method=POST
          filters:
            - name: AuthenticationFilter

        - id: payment-route
          uri: ${PAYMENT_ROUTE_ADDRESS}
          predicates:
            - Path=/payment/**
          filters:
            - name: AuthenticationFilter

        - id: post-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/post/**
            - Method=GET

        - id: post-route-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/post/**
            - Method=POST,PATCH,DELETE
          filters:
            - name: AuthenticationFilter

        - id: comment-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/comment/**
            - Method=GET

        - id: comment-route-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/comment/**
            - Method=POST,PATCH,DELETE
          filters:
            - name: AuthenticationFilter

        - id: comment-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/like/**
            - Method=GET

        - id: comment-route-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/like/**
            - Method=POST,PATCH,DELETE
          filters:
            - name: AuthenticationFilter

        - id: user-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/user/**
            - Method=GET

        - id: user-route-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/user/**
            - Method=PATCH,DELETE
          filters:
            - name: AuthenticationFilter

        - id: coffee-route-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/coffee/**
            - Method=POST
          filters:
            - name: AuthenticationFilter
logging:
  level:
    org:
      flow:
        gateway:
          common:
            log:
              LoggingFilter: INFO