spring:
  application:
    name: flow-api-gateway
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}
    access:
      expiration: ${ACCESS_EXPIRATION}
    refresh:
      expiration: ${REFRESH_EXPIRATION}
  cloud:
    gateway:
      routes:
        - id: main-auth-route
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/auth/**
          filters:
            - name: LoggingFilter
        - id: order-route
          uri: ${PAYMENT_ROUTE_ADDRESS}
          predicates:
            - Path=/order/**
          filters:
            - name: LoggingFilter
            - name: AuthenticationFilter
        - id: payment-route
          uri: ${PAYMENT_ROUTE_ADDRESS}
          predicates:
            - Path=/payment/**
          filters:
            - name: LoggingFilter
            - name: AuthenticationFilter